/**
 * Public Library — curated CC0 video clips from Pexels.
 *
 * The legal alternative to LYRC's user-uploaded library (which contains
 * pirated movie clips and has Disney/Marvel copyright exposure). Every
 * entry here links to a Pexels video published under the Pexels License
 * (free for commercial use, no attribution required, no copyright risk).
 *
 * Catalog is regenerated by `scripts/curate-public-clips.mjs` using a
 * PEXELS_API_KEY to search per-category and pick the top results. The
 * script writes to this file and we commit the result so the runtime
 * never needs to hit Pexels' rate-limited search endpoint.
 *
 * Direct CDN URLs at videos.pexels.com send `Access-Control-Allow-Origin: *`,
 * so the client can fetch them straight to ffmpeg.wasm without a proxy.
 */

export type PublicClipCategory =
  | "cinematic"
  | "city"
  | "performance"
  | "lifestyle"
  | "action"
  | "abstract"
  | "nature"
  | "romance";

export interface PublicClip {
  /** Pexels video id — stable across sessions */
  id: number;
  /** Human-readable label rendered on the tile */
  name: string;
  /** Curator's bucket — drives the filter chips */
  category: PublicClipCategory;
  /** Direct mp4 URL (videos.pexels.com CDN) — playable inline + downloadable for ffmpeg */
  mp4Url: string;
  /** Still preview from Pexels' image CDN — used as the tile thumbnail */
  thumbUrl: string;
  /** Length in seconds — surfaced on the tile so users know what they're picking */
  duration: number;
  /** Pixel dimensions — used to filter by aspect ratio if needed */
  width: number;
  height: number;
  /** Pexels page link for attribution / proof of license */
  pexelsUrl: string;
  /** Photographer / videographer credit */
  author: string;
}

export const PUBLIC_CLIP_CATEGORIES: { id: PublicClipCategory; label: string; emoji: string }[] = [
  { id: "cinematic",   label: "Cinematic",   emoji: "🎬" },
  { id: "city",        label: "City",        emoji: "🌃" },
  { id: "performance", label: "Performance", emoji: "🎤" },
  { id: "lifestyle",   label: "Lifestyle",   emoji: "☕" },
  { id: "action",      label: "Action",      emoji: "🏃" },
  { id: "abstract",    label: "Abstract",    emoji: "✨" },
  { id: "nature",      label: "Nature",      emoji: "🌊" },
  { id: "romance",     label: "Romance",     emoji: "💑" },
];

/**
 * Starter set — 1 verified entry from Pexels' public popular endpoint.
 * Run `node scripts/curate-public-clips.mjs` (with PEXELS_API_KEY set) to
 * regenerate the full catalog of ~100 clips across all categories.
 */
export const PUBLIC_CLIPS: PublicClip[] = [
  {
    id: 6963395,
    name: "Eucalyptus in soil",
    category: "lifestyle",
    mp4Url: "https://videos.pexels.com/video-files/6963395/6963395-hd_720_1280_50fps.mp4",
    thumbUrl: "https://images.pexels.com/videos/6963395/pictures/preview-0.jpeg",
    duration: 7,
    width: 720,
    height: 1280,
    pexelsUrl: "https://www.pexels.com/video/a-person-holding-a-eucalyptus-plant-with-soil-6963395/",
    author: "Cup of Couple",
  },
];

export function clipsByCategory(category: PublicClipCategory | "all"): PublicClip[] {
  if (category === "all") return PUBLIC_CLIPS;
  return PUBLIC_CLIPS.filter((c) => c.category === category);
}
